# -*- coding: utf-8 -*-
"""Face Parsing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDqUe8N2is17aqzZws0SvuNJhClxHVHv
"""

import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

!pip install -q transformers accelerate pillow matplotlib opencv-python

import torch
import numpy as np
import cv2
import matplotlib.pyplot as plt

from PIL import Image
from transformers import (
    SegformerImageProcessor,
    SegformerForSemanticSegmentation,
)

device = "cuda" if torch.cuda.is_available() else "cpu"

processor = SegformerImageProcessor.from_pretrained(
    "jonathandinu/face-parsing"
)

model = SegformerForSemanticSegmentation.from_pretrained(
    "jonathandinu/face-parsing"
)

model.to(device)
model.eval()

from google.colab import files

uploaded = files.upload()

image_path = list(uploaded.keys())[0]

image = Image.open(image_path).convert("RGB")
image

inputs = processor(images=image, return_tensors="pt").to(device)

with torch.no_grad():
    outputs = model(**inputs)

logits = outputs.logits

upsampled_logits = torch.nn.functional.interpolate(
    logits,
    size=image.size[::-1],
    mode="bilinear",
    align_corners=False,
)

labels = upsampled_logits.argmax(dim=1)[0]
labels = labels.cpu().numpy()

plt.figure(figsize=(8,8))
plt.imshow(labels)
plt.colorbar()
plt.axis("off")
plt.show()

label_map = {
    0: "background",
    1: "skin",
    2: "nose",
    3: "eye_g",
    4: "left_eye",
    5: "right_eye",
    6: "left_eyebrow",
    7: "right_eyebrow",
    8: "left_ear",
    9: "right_ear",
    10: "mouth",
    11: "upper_lip",
    12: "lower_lip",
    13: "hair",
    14: "hat",
    15: "earring",
    16: "necklace",
    17: "neck",
    18: "cloth",
}

fig, axes = plt.subplots(4,5, figsize=(15,12))

axes = axes.flatten()

for idx, name in label_map.items():
    mask = (labels == idx)

    axes[idx].imshow(mask, cmap="gray")
    axes[idx].set_title(name)
    axes[idx].axis("off")

plt.tight_layout()
plt.show()

# import os
# img = np.array(image)

# os.makedirs("parts-2", exist_ok=True)

# for idx, name in label_map.items():

#     mask = (labels == idx)

#     part = np.zeros_like(img)
#     part[mask] = img[mask]

#     cv2.imwrite(
#         f"parts-2/{name}.png",
#         cv2.cvtColor(part, cv2.COLOR_RGB2BGR)
#     )

# os.makedirs("parts-cropped-2", exist_ok=True)

# for idx, name in label_map.items():

#     mask = (labels == idx).astype(np.uint8)

#     ys, xs = np.where(mask)

#     if len(xs) == 0:
#         continue

#     x1, x2 = xs.min(), xs.max()
#     y1, y2 = ys.min(), ys.max()

#     crop = np.array(image)[y1:y2+1, x1:x2+1]

#     Image.fromarray(crop).save(f"parts-cropped-2/{name}_crop.png")

# !zip -r /content/parts-2.zip /content/parts-2

# # 2. Trigger the browser download
# from google.colab import files
# files.download('/content/parts-2.zip')

import numpy as np
import matplotlib.pyplot as plt

img = np.array(image)

rows = 4
cols = 5

fig, axes = plt.subplots(rows, cols, figsize=(18,14))
axes = axes.flatten()

for idx in range(len(label_map)):

    mask = labels == idx

    part = np.zeros_like(img)
    part[mask] = img[mask]

    axes[idx].imshow(part)
    axes[idx].set_title(label_map[idx], fontsize=11)
    axes[idx].axis("off")

for i in range(len(label_map), len(axes)):
    axes[i].axis("off")

plt.tight_layout()
plt.show()

# for i in range(len(label_map), len(axes)):
#     axes[i].axis("off")

# plt.tight_layout()

# # Save the figure BEFORE plt.show()
# plt.savefig("my_segmented_image.png", dpi=300, bbox_inches='tight')

# plt.show()

import numpy as np
import matplotlib.pyplot as plt

img = np.array(image)

rows = 4
cols = 5

fig, axes = plt.subplots(rows, cols, figsize=(18,14))
axes = axes.flatten()

for idx in range(len(label_map)):

    mask = (labels == idx)

    ys, xs = np.where(mask)

    if len(xs) == 0:
        axes[idx].axis("off")
        continue

    x1, x2 = xs.min(), xs.max()
    y1, y2 = ys.min(), ys.max()

    crop = img[y1:y2+1, x1:x2+1]

    axes[idx].imshow(crop)
    axes[idx].set_title(label_map[idx], fontsize=11)
    axes[idx].axis("off")

for i in range(len(label_map), len(axes)):
    axes[i].axis("off")

plt.tight_layout()
plt.show()

# plt.tight_layout()

# plt.savefig(
#     "all_body_parts.png",
#     dpi=300,
#     bbox_inches="tight"
# )

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

img = np.array(image)

# Combine all lip-related classes
lip_mask = np.isin(labels, [10, 11, 12])

# Create segmented image
lip_region = np.zeros_like(img)
lip_region[lip_mask] = img[lip_mask]

# Crop tightly
ys, xs = np.where(lip_mask)

x1, x2 = xs.min(), xs.max()
y1, y2 = ys.min(), ys.max()

lip_crop = lip_region[y1:y2+1, x1:x2+1]

plt.figure(figsize=(5,3))
plt.imshow(lip_crop)
plt.title("Lips")
plt.axis("off")
plt.show()

original_crop = img[y1:y2+1, x1:x2+1]

plt.imshow(original_crop)
plt.axis("off")
plt.show()

# Image.fromarray(original_crop).save("Lips_original.png")

!pip install protobuf==5.29.5
!pip install tensorflow==2.19.0
!pip install mediapipe==0.10.21

import mediapipe as mp
import pandas as pd

REAL_IPD_MM = 63.0  # average adult inter-pupillary distance

mp_face_mesh = mp.solutions.face_mesh

img_rgb = np.array(image)
h, w = img_rgb.shape[:2]

with mp_face_mesh.FaceMesh(
    static_image_mode=True,
    max_num_faces=1,
    refine_landmarks=True,       # needed to get iris landmarks (468-477)
    min_detection_confidence=0.5,
) as face_mesh:
    mp_results = face_mesh.process(img_rgb)

if not mp_results.multi_face_landmarks:
    raise RuntimeError("MediaPipe Face Mesh did not detect a face in this image.")

face_landmarks = mp_results.multi_face_landmarks[0].landmark

def lm_px(idx):
    """Pixel coordinates of a Face Mesh landmark index."""
    lm = face_landmarks[idx]
    return np.array([lm.x * w, lm.y * h])

def dist_px(idx1, idx2):
    return float(np.linalg.norm(lm_px(idx1) - lm_px(idx2)))

# Iris center landmark indices (only present when refine_landmarks=True)
LEFT_IRIS_CENTER = 468
RIGHT_IRIS_CENTER = 473

ipd_px = dist_px(LEFT_IRIS_CENTER, RIGHT_IRIS_CENTER)
mm_per_px = REAL_IPD_MM / ipd_px

print(f"Inter-pupillary distance: {ipd_px:.2f} px")
print(f"Scale factor: {mm_per_px:.5f} mm/px  (using REAL_IPD_MM={REAL_IPD_MM})")

# --- Visualize the two pupil points used for calibration ---
vis = img_rgb.copy()
for idx, color in [(LEFT_IRIS_CENTER, (255, 0, 0)), (RIGHT_IRIS_CENTER, (0, 0, 255))]:
    x, y = lm_px(idx).astype(int)
    cv2.circle(vis, (x, y), 4, color, -1)

plt.figure(figsize=(6, 6))
plt.imshow(vis)
plt.title(f"IPD calibration: {ipd_px:.1f}px -> {REAL_IPD_MM}mm")
plt.axis("off")
plt.show()

# ------------------------------------------------------------
# (A) Direct landmark-to-landmark measurements (most accurate)
# ------------------------------------------------------------
FACE_LANDMARK_PAIRS = {
    "face_width":       (234, 454),   # left cheek <-> right cheek
    "face_height":      (10, 152),    # forehead <-> chin
    "mouth_width":      (61, 291),    # left <-> right mouth corner
    "left_eye_width":   (33, 133),
    "right_eye_width":  (362, 263),
    "nose_width":       (129, 358),   # left <-> right nostril wing
    "nose_height":      (168, 2),     # nose bridge top <-> nose base
    "left_eyebrow_len": (70, 105),
    "right_eyebrow_len":(300, 336),
    "jaw_width":        (58, 288),
}

landmark_measurements = {
    name: round(dist_px(i1, i2) * mm_per_px, 2)
    for name, (i1, i2) in FACE_LANDMARK_PAIRS.items()
}

landmark_df = pd.DataFrame.from_dict(
    landmark_measurements, orient="index", columns=["size_mm"]
)
print("\nLandmark-based measurements (mm):")
print(landmark_df)

# ------------------------------------------------------------
# (B) Segmentation-mask bounding-box measurements (from the
#     face-parsing model output computed earlier: `labels`)
# ------------------------------------------------------------
def measure_mask(mask):
    ys, xs = np.where(mask)
    if len(xs) == 0:
        return None
    x1, x2 = xs.min(), xs.max()
    y1, y2 = ys.min(), ys.max()
    width_px = x2 - x1 + 1
    height_px = y2 - y1 + 1
    return {
        "width_px": int(width_px),
        "height_px": int(height_px),
        "width_mm": round(width_px * mm_per_px, 2),
        "height_mm": round(height_px * mm_per_px, 2),
    }

segmentation_measurements = {}
for idx, name in label_map.items():
    if name in ("background", "hat", "cloth"):
        continue
    mask = (labels == idx)
    result = measure_mask(mask)
    if result:
        segmentation_measurements[name] = result

seg_df = pd.DataFrame(segmentation_measurements).T
print("\nSegmentation bounding-box measurements (px & mm):")
print(seg_df)

# Optional: save both tables to CSV
landmark_df.to_csv("landmark_measurements_mm.csv")
seg_df.to_csv("segmentation_measurements.csv")

"""for eyebrow:
- brow peak vertical height
- ekevation ration
- bow apex angle

for eye:
- eye aspect ration ( almondness ration)
- eye spacing ratio ( interpupillary / facial width)
- lower eyelif curvature

for nose:
- naso canthal ratio
- pyramidal width
- nasal aspect ratio

for lips:
- mouth width
- philitrum length
- cupids bow angle

cheeks:
facial width
makar width ratio ( powells method)
cheek bone position

jaw
 forntial jaw rise
 jaw width
 jaw inclination angle
 facial width

chin
chin width
chin vertical height
deviation of chin midline symmetry

hair
forehead width
forehead height
temple mod angle

smile
upper simle arc
lower smile arc
smile width

neck
neck width
neck width to jaw ratio
neck length



"""

import mediapipe as mp
import pandas as pd

REAL_IPD_MM = 63.0  # average adult inter-pupillary distance

mp_face_mesh = mp.solutions.face_mesh

img_rgb = np.array(image)
h, w = img_rgb.shape[:2]

with mp_face_mesh.FaceMesh(
    static_image_mode=True,
    max_num_faces=1,
    refine_landmarks=True,       # needed to get iris landmarks (468-477)
    min_detection_confidence=0.5,
) as face_mesh:
    mp_results = face_mesh.process(img_rgb)

if not mp_results.multi_face_landmarks:
    raise RuntimeError("MediaPipe Face Mesh did not detect a face in this image.")

face_landmarks = mp_results.multi_face_landmarks[0].landmark

def lm_px(idx):
    """Pixel coordinates of a Face Mesh landmark index."""
    lm = face_landmarks[idx]
    return np.array([lm.x * w, lm.y * h])

def dist_px(idx1, idx2):
    return float(np.linalg.norm(lm_px(idx1) - lm_px(idx2)))

# Iris center landmark indices (only present when refine_landmarks=True)
LEFT_IRIS_CENTER = 468
RIGHT_IRIS_CENTER = 473

ipd_px = dist_px(LEFT_IRIS_CENTER, RIGHT_IRIS_CENTER)
mm_per_px = REAL_IPD_MM / ipd_px

print(f"Inter-pupillary distance: {ipd_px:.2f} px")
print(f"Scale factor: {mm_per_px:.5f} mm/px  (using REAL_IPD_MM={REAL_IPD_MM})")

# --- Visualize the two pupil points used for calibration ---
vis = img_rgb.copy()
for idx, color in [(LEFT_IRIS_CENTER, (255, 0, 0)), (RIGHT_IRIS_CENTER, (0, 0, 255))]:
    x, y = lm_px(idx).astype(int)
    cv2.circle(vis, (x, y), 4, color, -1)

plt.figure(figsize=(6, 6))
plt.imshow(vis)
plt.title(f"IPD calibration: {ipd_px:.1f}px -> {REAL_IPD_MM}mm")
plt.axis("off")
plt.show()

# ------------------------------------------------------------
# (A) Direct landmark-to-landmark measurements (most accurate)
# ------------------------------------------------------------
FACE_LANDMARK_PAIRS = {
    "face_width":       (234, 454),   # left cheek <-> right cheek
    "face_height":      (10, 152),    # forehead <-> chin
    "mouth_width":      (61, 291),    # left <-> right mouth corner
    "left_eye_width":   (33, 133),
    "right_eye_width":  (362, 263),
    "nose_width":       (129, 358),   # left <-> right nostril wing
    "nose_height":      (168, 2),     # nose bridge top <-> nose base
    "left_eyebrow_len": (70, 105),
    "right_eyebrow_len":(300, 336),
    "jaw_width":        (58, 288),
}

landmark_measurements = {
    name: round(dist_px(i1, i2) * mm_per_px, 2)
    for name, (i1, i2) in FACE_LANDMARK_PAIRS.items()
}

landmark_df = pd.DataFrame.from_dict(
    landmark_measurements, orient="index", columns=["size_mm"]
)
print("\nLandmark-based measurements (mm):")
print(landmark_df)

# ------------------------------------------------------------
# (B) Segmentation-mask bounding-box measurements (from the
#     face-parsing model output computed earlier: `labels`)
# ------------------------------------------------------------
def measure_mask(mask):
    ys, xs = np.where(mask)
    if len(xs) == 0:
        return None
    x1, x2 = xs.min(), xs.max()
    y1, y2 = ys.min(), ys.max()
    width_px = x2 - x1 + 1
    height_px = y2 - y1 + 1
    return {
        "width_px": int(width_px),
        "height_px": int(height_px),
        "width_mm": round(width_px * mm_per_px, 2),
        "height_mm": round(height_px * mm_per_px, 2),
    }

segmentation_measurements = {}
for idx, name in label_map.items():
    if name in ("background", "hat", "cloth"):
        continue
    mask = (labels == idx)
    result = measure_mask(mask)
    if result:
        segmentation_measurements[name] = result

seg_df = pd.DataFrame(segmentation_measurements).T
print("\nSegmentation bounding-box measurements (px & mm):")
print(seg_df)

# Optional: save both tables to CSV
landmark_df.to_csv("landmark_measurements_mm.csv")
seg_df.to_csv("segmentation_measurements.csv")

# ============================================================
# EXTENDED FACIAL METRICS
# ============================================================
# Builds on `face_landmarks`, `lm_px`, `dist_px`, `mm_per_px`, `w`, `h`
# defined in the MediaPipe section above. Reuses `labels` (face-parsing
# segmentation mask) for the neck, which Face Mesh does not cover.
#
# IMPORTANT ACCURACY NOTE:
# MediaPipe Face Mesh's 468(+iris) points are a generic 3D face model,
# not clinical/anthropometric landmarks (glabella, gonion, zygion,
# tragion, menton, etc.). The indices below are commonly-used, best
# -effort proxies for those anatomical points. If you need clinical-
# grade precision, use `plot_landmark_debug()` below to visually
# verify/adjust the indices for your specific image before trusting
# the numbers.

def plot_landmark_debug(indices, labels_text=None, title="Landmark check"):
    """Overlay chosen landmark indices on the image so you can verify
    they land where you expect before trusting downstream metrics."""
    vis = img_rgb.copy()
    for i, idx in enumerate(indices):
        x, y = lm_px(idx).astype(int)
        cv2.circle(vis, (x, y), 3, (255, 0, 0), -1)
        text = labels_text[i] if labels_text else str(idx)
        cv2.putText(vis, text, (x + 4, y - 4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 255, 0), 1, cv2.LINE_AA)
    plt.figure(figsize=(7, 7))
    plt.imshow(vis)
    plt.title(title)
    plt.axis("off")
    plt.show()

def angle_deg(vertex_idx, a_idx, b_idx):
    """Angle (deg) at `vertex` between rays vertex->a and vertex->b."""
    v, a, b = lm_px(vertex_idx), lm_px(a_idx), lm_px(b_idx)
    va, vb = a - v, b - v
    cos_a = np.dot(va, vb) / (np.linalg.norm(va) * np.linalg.norm(vb) + 1e-9)
    return float(np.degrees(np.arccos(np.clip(cos_a, -1, 1))))

def angle_from_vertical(idx_top, idx_bottom):
    vec = lm_px(idx_bottom) - lm_px(idx_top)
    cos_a = np.dot(vec, [0, 1]) / (np.linalg.norm(vec) + 1e-9)
    return float(np.degrees(np.arccos(np.clip(cos_a, -1, 1))))

def angle_from_horizontal(idx_a, idx_b):
    vec = lm_px(idx_b) - lm_px(idx_a)
    cos_a = np.dot(vec, [1, 0]) / (np.linalg.norm(vec) + 1e-9)
    return float(np.degrees(np.arccos(np.clip(cos_a, -1, 1))))

def curvature_ratio(p_start_idx, p_mid_idx, p_end_idx):
    """Sagitta/chord ratio: 0 = flat line, higher = more arched/curved."""
    p1, p2, p3 = lm_px(p_start_idx), lm_px(p_mid_idx), lm_px(p_end_idx)
    chord = p3 - p1
    chord_len = np.linalg.norm(chord)
    if chord_len < 1e-6:
        return 0.0
    # perpendicular distance of p2 from the line p1-p3 (the sagitta)
    t = np.dot(p2 - p1, chord) / (chord_len ** 2)
    proj = p1 + t * chord
    sagitta = np.linalg.norm(p2 - proj)
    return float(sagitta / chord_len)

def eye_aspect_ratio(p1, p2, p3, p4, p5, p6):
    """Classic EAR: (|p2-p6| + |p3-p5|) / (2*|p1-p4|)."""
    p1, p2, p3, p4, p5, p6 = [lm_px(i) for i in (p1, p2, p3, p4, p5, p6)]
    vertical = np.linalg.norm(p2 - p6) + np.linalg.norm(p3 - p5)
    horizontal = np.linalg.norm(p1 - p4)
    return float(vertical / (2 * horizontal + 1e-9))

def point_line_deviation_px(point_idx, line_idx1, line_idx2):
    """Perpendicular distance (px) of `point` from line (line1, line2)."""
    p, a, b = lm_px(point_idx), lm_px(line_idx1), lm_px(line_idx2)
    ab = b - a
    t = np.dot(p - a, ab) / (np.dot(ab, ab) + 1e-9)
    proj = a + t * ab
    return float(np.linalg.norm(p - proj))

# --- reference / anchor landmarks -----------------------------------
FOREHEAD_TOP   = 10
GLABELLA       = 9      # between eyebrows
NOSE_TIP       = 4
NOSE_BRIDGE    = 168
SUBNASALE      = 2      # nose base
MENTON         = 152     # chin bottom
R_ZYGION       = 234     # right cheekbone (image-right)
L_ZYGION       = 454     # left cheekbone
R_TEMPLE       = 127
L_TEMPLE       = 356
R_GONION       = 172     # right jaw angle (image-right)
L_GONION       = 397     # left jaw angle

face_width_px  = dist_px(R_ZYGION, L_ZYGION)
face_height_px = dist_px(FOREHEAD_TOP, MENTON)

metrics = {}  # category -> {metric_name: (value, unit)}

# ---------------- EYEBROWS -------------------------------------------
R_BROW_INNER, R_BROW_PEAK, R_BROW_OUTER = 55, 105, 70
L_BROW_INNER, L_BROW_PEAK, L_BROW_OUTER = 285, 334, 300
R_EYE_TOP, R_EYE_BOTTOM = 159, 145
L_EYE_TOP, L_EYE_BOTTOM = 386, 374

metrics["eyebrow"] = {
    "right_brow_peak_vertical_height_mm": (
        abs(lm_px(R_BROW_PEAK)[1] - lm_px(R_EYE_TOP)[1]) * mm_per_px, "mm"),
    "left_brow_peak_vertical_height_mm": (
        abs(lm_px(L_BROW_PEAK)[1] - lm_px(L_EYE_TOP)[1]) * mm_per_px, "mm"),
    "right_brow_elevation_ratio": (
        abs(lm_px(R_BROW_PEAK)[1] - lm_px(R_EYE_TOP)[1]) / (ipd_px + 1e-9), "ratio"),
    "left_brow_elevation_ratio": (
        abs(lm_px(L_BROW_PEAK)[1] - lm_px(L_EYE_TOP)[1]) / (ipd_px + 1e-9), "ratio"),
    "right_brow_apex_angle_deg": (
        angle_deg(R_BROW_PEAK, R_BROW_INNER, R_BROW_OUTER), "deg"),
    "left_brow_apex_angle_deg": (
        angle_deg(L_BROW_PEAK, L_BROW_INNER, L_BROW_OUTER), "deg"),
}

# ---------------- EYES -------------------------------------------------
metrics["eye"] = {
    "right_eye_aspect_ratio": (
        eye_aspect_ratio(33, 160, 158, 133, 153, 144), "ratio"),
    "left_eye_aspect_ratio": (
        eye_aspect_ratio(362, 385, 387, 263, 373, 380), "ratio"),
    "eye_spacing_ratio_ipd_over_face_width": (
        ipd_px / (face_width_px + 1e-9), "ratio"),
    "right_lower_eyelid_curvature": (
        curvature_ratio(33, R_EYE_BOTTOM, 133), "ratio"),
    "left_lower_eyelid_curvature": (
        curvature_ratio(362, L_EYE_BOTTOM, 263), "ratio"),
}

# ---------------- NOSE ---------------------------------------------
R_ALA, L_ALA = 129, 358          # nostril wings
R_BRIDGE_SIDE, L_BRIDGE_SIDE = 236, 456   # nasal sidewalls (pyramidal width)
R_INNER_CANTHUS, L_INNER_CANTHUS = 133, 362

nose_width_px = dist_px(R_ALA, L_ALA)
nose_height_px = dist_px(NOSE_BRIDGE, SUBNASALE)
intercanthal_px = dist_px(R_INNER_CANTHUS, L_INNER_CANTHUS)

metrics["nose"] = {
    "naso_canthal_ratio_nose_width_over_intercanthal": (
        nose_width_px / (intercanthal_px + 1e-9), "ratio"),
    "pyramidal_width_mm": (
        dist_px(R_BRIDGE_SIDE, L_BRIDGE_SIDE) * mm_per_px, "mm"),
    "nasal_aspect_ratio_width_over_height": (
        nose_width_px / (nose_height_px + 1e-9), "ratio"),
    "nose_width_mm": (nose_width_px * mm_per_px, "mm"),
    "nose_height_mm": (nose_height_px * mm_per_px, "mm"),
}

# ---------------- LIPS -----------------------------------------------
MOUTH_R, MOUTH_L = 61, 291
CUPID_DIP = 0
CUPID_PEAK_R, CUPID_PEAK_L = 37, 267
LOWER_LIP_BOTTOM = 17

mouth_width_px = dist_px(MOUTH_R, MOUTH_L)

metrics["lips"] = {
    "mouth_width_mm": (mouth_width_px * mm_per_px, "mm"),
    "philtrum_length_mm": (dist_px(SUBNASALE, CUPID_DIP) * mm_per_px, "mm"),
    "cupids_bow_angle_deg": (
        angle_deg(CUPID_DIP, CUPID_PEAK_R, CUPID_PEAK_L), "deg"),
}

# ---------------- CHEEKS ----------------------------------------------
metrics["cheeks"] = {
    "facial_width_mm": (face_width_px * mm_per_px, "mm"),
    "malar_width_ratio_powell": (
        face_width_px / (face_height_px + 1e-9), "ratio"),
    "right_cheekbone_vertical_position_ratio": (
        (lm_px(R_ZYGION)[1] - lm_px(FOREHEAD_TOP)[1]) / (face_height_px + 1e-9), "ratio (0=forehead,1=chin)"),
    "left_cheekbone_vertical_position_ratio": (
        (lm_px(L_ZYGION)[1] - lm_px(FOREHEAD_TOP)[1]) / (face_height_px + 1e-9), "ratio (0=forehead,1=chin)"),
}

# ---------------- JAW --------------------------------------------------
jaw_width_px = dist_px(R_GONION, L_GONION)

metrics["jaw"] = {
    "frontal_jaw_rise_mm": (
        abs(lm_px(R_GONION)[1] - lm_px(MENTON)[1]) * mm_per_px, "mm"),
    "jaw_width_mm": (jaw_width_px * mm_per_px, "mm"),
    "right_jaw_inclination_angle_deg": (
        angle_from_horizontal(R_GONION, MENTON), "deg"),
    "left_jaw_inclination_angle_deg": (
        angle_from_horizontal(L_GONION, MENTON), "deg"),
    "facial_width_mm": (face_width_px * mm_per_px, "mm"),
}

# ---------------- CHIN --------------------------------------------------
CHIN_R, CHIN_L = 214, 434  # approx chin-side taper points

metrics["chin"] = {
    "chin_width_mm": (dist_px(CHIN_R, CHIN_L) * mm_per_px, "mm"),
    "chin_vertical_height_mm": (
        dist_px(LOWER_LIP_BOTTOM, MENTON) * mm_per_px, "mm"),
    "chin_midline_deviation_mm": (
        point_line_deviation_px(MENTON, GLABELLA, NOSE_TIP) * mm_per_px, "mm"),
}

# ---------------- HAIR / FOREHEAD ---------------------------------------
# NOTE: Face Mesh has no true hairline landmark; forehead_height below
# only measures the *visible mesh* forehead (top-of-mesh to glabella),
# not the anatomical hairline-to-brow distance.
metrics["hair"] = {
    "forehead_width_mm": (dist_px(R_TEMPLE, L_TEMPLE) * mm_per_px, "mm"),
    "forehead_height_mm_mesh_approx": (
        dist_px(FOREHEAD_TOP, GLABELLA) * mm_per_px, "mm"),
    "right_temple_mod_angle_deg": (
        angle_from_vertical(R_TEMPLE, R_ZYGION), "deg"),
    "left_temple_mod_angle_deg": (
        angle_from_vertical(L_TEMPLE, L_ZYGION), "deg"),
}

# ---------------- SMILE ---------------------------------------------
# NOTE: these reflect whatever expression is in the photo — for a true
# "smile arc" you need a smiling photo; on a neutral face they still
# compute (just describing the resting lip curve).
metrics["smile"] = {
    "upper_smile_arc_curvature": (
        curvature_ratio(MOUTH_R, CUPID_DIP, MOUTH_L), "ratio"),
    "lower_smile_arc_curvature": (
        curvature_ratio(MOUTH_R, LOWER_LIP_BOTTOM, MOUTH_L), "ratio"),
    "smile_width_mm": (mouth_width_px * mm_per_px, "mm"),
}

# ---------------- NECK ---------------------------------------------
# Face Mesh has no neck landmarks -> use the face-parsing segmentation
# mask (label 17 = "neck") computed earlier as `labels`.
neck_mask = (labels == 17)
neck_result = measure_mask(neck_mask)

if neck_result:
    metrics["neck"] = {
        "neck_width_mm": (neck_result["width_mm"], "mm"),
        "neck_width_to_jaw_width_ratio": (
            neck_result["width_mm"] / ((jaw_width_px * mm_per_px) + 1e-9), "ratio"),
    }
else:
    metrics["neck"] = {
        "neck_width_mm": (None, "mm — neck not detected in segmentation mask"),
        "neck_width_to_jaw_width_ratio": (None, "ratio"),
    }

# ---------------- Flatten into one DataFrame -------------------------
rows = []
for category, m in metrics.items():
    for name, (value, unit) in m.items():
        rows.append({
            "category": category,
            "metric": name,
            "value": round(value, 3) if isinstance(value, (int, float)) else value,
            "unit": unit,
        })

extended_metrics_df = pd.DataFrame(rows)
print(extended_metrics_df.to_string(index=False))

extended_metrics_df.to_csv("extended_facial_metrics.csv", index=False)

# Uncomment to visually sanity-check any set of indices, e.g.:
plot_landmark_debug(
    [R_BROW_PEAK, L_BROW_PEAK, R_GONION, L_GONION, CHIN_R, CHIN_L],
    ["r_brow_peak", "l_brow_peak", "r_gonion", "l_gonion", "chin_r", "chin_l"],
)

