# -*- coding: utf-8 -*-
"""extract_hair_colab (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyOajLers5_blT_8-ZNTQJ9pt9EwrSzu

# Hair Extraction & Visualization - Google Colab
Extract and display hair region from face parsing segmentation.
Uses Google Drive for model and image storage.

## 1. Mount Google Drive
"""

!pip install -q transformers accelerate pillow matplotlib opencv-python

from google.colab import drive
drive.mount('/content/drive')
print("✓ Google Drive mounted successfully")

"""## 2. Setup & Dependencies"""

import torch
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os
from PIL import Image
from transformers import (
    SegformerImageProcessor,
    SegformerForSemanticSegmentation,
)

# Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"✓ Using device: {device}")
if device == "cuda":
    print(f"✓ GPU: {torch.cuda.get_device_name(0)}")

"""## 3. Load Model from Google Drive"""

# CONFIGURATION - Update these paths to match your Google Drive structure
# Example structure:
# My Drive/
#   ├── face_parsing/  (model folder)
#   └── images/
#       └── side.png

model_folder_path = "/content/drive/MyDrive/face-parsing"
image_path = "/content/i.png"

print(f"Model path: {model_folder_path}")
print(f"Image path: {image_path}")
print()

# Check if paths exist
if os.path.exists(model_folder_path):
    print(f"✓ Model folder found")
    files = os.listdir(model_folder_path)
    print(f"  Contents: {files[:5]}..." if len(files) > 5 else f"  Contents: {files}")
else:
    print(f"✗ Model folder not found at: {model_folder_path}")
    print("  Please update model_folder_path in cell above")
    print()

if os.path.exists(image_path):
    print(f"✓ Image file found")
else:
    print(f"✗ Image file not found at: {image_path}")
    print("  Please update image_path in cell above")

"""## 4. Load Face Parsing Model from Google Drive"""

try:
    print("Loading model from Google Drive...")
    processor = SegformerImageProcessor.from_pretrained(model_folder_path)
    model = SegformerForSemanticSegmentation.from_pretrained(model_folder_path)
    model.to(device)
    model.eval()
    print("✓ Face Parsing Model Loaded Successfully")
    print(f"  Device: {device}")
except Exception as e:
    print(f"✗ Error loading model: {e}")
    print("Please ensure the face_parsing folder is in your Google Drive")

"""## 5. Load Image from Google Drive"""

try:
    image = Image.open(image_path).convert("RGB")
    img_rgb = np.array(image)
    print(f"✓ Image loaded: {image.size}")
    print(f"  Shape: {img_rgb.shape}")

    # Display original image
    plt.figure(figsize=(10, 8))
    plt.imshow(img_rgb)
    plt.title("Original Image", fontsize=14, fontweight="bold")
    plt.axis("off")
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f"✗ Error loading image: {e}")
    print("Please ensure the image file exists at the specified path")

"""## 6. Run Face Segmentation"""

print("Running face segmentation...")

# Run segmentation
inputs = processor(images=image, return_tensors="pt").to(device)

with torch.no_grad():
    outputs = model(**inputs)

logits = outputs.logits

# Upsample to original image size
upsampled_logits = torch.nn.functional.interpolate(
    logits,
    size=image.size[::-1],
    mode="bilinear",
    align_corners=False,
)

labels = upsampled_logits.argmax(dim=1)[0]
labels = labels.cpu().numpy()

print(f"✓ Segmentation complete")
print(f"Unique labels detected: {sorted(np.unique(labels))}")

"""## 7. Define Facial Part Labels"""

LABEL_MAP = {
    0: "background",
    1: "skin",
    2: "nose",
    3: "eye_g",
    4: "left_eye",
    5: "right_eye",
    6: "left_eyebrow",
    7: "right_eyebrow",
    8: "left_ear",
    9: "right_ear",
    10: "mouth",
    11: "upper_lip",
    12: "lower_lip",
    13: "hair",
    14: "hat",
    15: "earring",
    16: "necklace",
    17: "neck",
    18: "cloth",
}

print(f"Total facial regions: {len(LABEL_MAP)}")

# Hair label ID is 13
HAIR_LABEL = 13

# Create hair mask
hair_mask = (labels == HAIR_LABEL)

# Statistics
hair_pixel_count = np.sum(hair_mask)
total_pixels = hair_mask.size
hair_coverage = (hair_pixel_count / total_pixels * 100)

print(f"\n{'='*60}")
print("HAIR EXTRACTION RESULTS")
print(f"{'='*60}")
print(f"Hair pixels detected: {hair_pixel_count:,}")
print(f"Total image pixels: {total_pixels:,}")
print(f"Hair coverage: {hair_coverage:.2f}%")
print(f"{'='*60}\n")

"""## 18. Hair Color Analysis"""

from sklearn.cluster import KMeans
from collections import Counter

print("Analyzing hair colors...\n")

# Extract hair pixels from original image
hair_pixels = img_rgb[hair_mask]

print(f"Total hair pixels for analysis: {len(hair_pixels):,}")

# Use KMeans to find dominant colors
n_colors = 5  # Number of dominant colors to extract
kmeans = KMeans(n_clusters=n_colors, random_state=42, n_init=10)
kmeans.fit(hair_pixels)

# Get cluster centers (dominant colors)
dominant_colors = kmeans.cluster_centers_.astype(int)
labels_kmeans = kmeans.labels_

# Get color distribution
color_distribution = Counter(labels_kmeans)
total_hair_pixels = len(labels_kmeans)

# Sort by frequency
sorted_colors = sorted(color_distribution.items(), key=lambda x: x[1], reverse=True)

print(f"\n{'='*60}")
print("DOMINANT HAIR COLORS")
print(f"{'='*60}")

color_info = []
for idx, (color_idx, count) in enumerate(sorted_colors, 1):
    rgb = dominant_colors[color_idx]
    hex_color = '#{:02x}{:02x}{:02x}'.format(rgb[0], rgb[1], rgb[2])
    percentage = (count / total_hair_pixels) * 100
    color_info.append({
        'rank': idx,
        'rgb': rgb,
        'hex': hex_color,
        'percentage': percentage,
        'count': count
    })
    print(f"{idx}. {hex_color} - RGB{tuple(rgb)} - {percentage:.2f}% ({count:,} pixels)")

print(f"{'='*60}\n")

"""## 20. Hair Color Category Classification"""

def classify_hair_color(hex_color):
    """
    Classify hair color into categories based on hex color.
    """
    hex_color = hex_color.lstrip('#')
    r, g, b = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16)

    # Calculate brightness
    brightness = (r + g + b) / 3

    # Calculate color dominance
    if r > g and r > b:
        if brightness > 200:
            return "Light/Golden Blonde"
        elif brightness > 150:
            return "Dark Blonde/Honey"
        elif brightness > 100:
            return "Light Brown/Chestnut"
        elif brightness > 50:
            return "Dark Brown"
        else:
            return "Black/Very Dark Brown"
    elif g > r and g > b:
        return "Green/Dyed Hair"
    elif b > r and b > g:
        return "Blue/Dyed Hair"
    else:
        # Neutral - use brightness as tiebreaker
        if brightness > 200:
            return "Platinum/Light Blonde"
        elif brightness > 150:
            return "Light Brown/Ash Blonde"
        elif brightness > 100:
            return "Medium Brown"
        elif brightness > 50:
            return "Dark Brown"
        else:
            return "Black/Very Dark Brown"

# Classify primary hair color
primary_color = color_info[0]
primary_hex = primary_color['hex']
hair_category = classify_hair_color(primary_hex)

print(f"\n{'='*60}")
print("HAIR COLOR CLASSIFICATION")
print(f"{'='*60}")
print(f"\nPrimary Hair Color: {primary_hex}")
print(f"Hair Category: {hair_category}")
print(f"Coverage: {primary_color['percentage']:.2f}%")
print(f"\nAll Color Categories:")

for info in color_info:
    category = classify_hair_color(info['hex'])
    print(f"  {info['hex']} ({info['percentage']:.1f}%) → {category}")

print(f"{'='*60}\n")